# This file contains the Kubernetes configuration for deploying PostgreSQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  namespace: rodent-platform
spec:
  capacity: { storage: 10Gi }
  accessModes: [ReadWriteOnce]
  storageClassName: local-static
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/block/postgres_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["node1"]     # change if your node name differs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: rodent-platform
spec:
  storageClassName: local-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    volumeName: pv-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: rodent-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "mlflowdb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rodent-platform
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432